"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import { useState, useEffect, Children } from "react";
import React, {Fragment} from "react";





const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;

}>) {
  const [cart, setcart] = useState<any>({})
  const [subtotal, setsubtotal] = useState<number>(0)
  
  useEffect(() => {
    console.log("hello bro")
    try {
      const cartData = localStorage.getItem("cart");
      if (cartData !== null) {
        setcart(JSON.parse(cartData));
      }
     
    } catch (error) {
      console.error(error)
    }
    
    
  }, [])
  const savecart = (mycart: any): void => {
    localStorage.setItem("cart", mycart)
    let subt = 0
    const keys = Object.keys(cart)
    for (let i = 0; i < keys.length; i++) {
      subt += mycart[keys[i]].price * mycart[keys[i]].qty
    }
    setsubtotal(subt)

  }
  const addtocart = (itemid: number, qty: number, price: number, name: string, size: string, varient: string): void => {
    let newcart = cart
    if (itemid in cart) {
      newcart[itemid].qty = cart[itemid].qty + qty
    }
    else {
      newcart[itemid] = { qty: 1, price, name, size, varient }
    }
    setcart(newcart)
    savecart(newcart)
  }
  const removetocart = (itemid: number, qty: number, price: number, name: string, size: string, varient: string): void => {
    let newcart = cart
    if (itemid in cart) {
      newcart[itemid].qty = cart[itemid].qty + qty
    }
    if (newcart[itemid]["qty"] <= 0) {
      delete newcart[itemid]
    }
    setcart(newcart)
    savecart(newcart)
  }
  const clearcart = (): void => {
    setcart({})
    savecart({})
    console.log("clear cart")
  }
  return (
    <>

      <html lang="en">
        {/* <Navbar/> */}
        <body className={inter.className}>
          <title>hello</title>
          
          <Navbar cart={cart} addtocart={addtocart} removetocart={removetocart} clearcart={clearcart} subtotal={subtotal}/>
          
          {children}
          <Footer />
          
        </body>
        {/* <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"/> */}

      </html>

    </>
  );
}