"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../../components/Footer";
import React from "react";
import { Appwrapper } from "@/context/layout";
import Navbar from "../../components/Navbar";


const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <>

      <html lang="en">
        {/* <Navbar/> */}
        <body className={inter.className}>
          <title>hello</title>
          
         <Appwrapper>
          <Navbar/>
          {children}
          <Footer />
          </Appwrapper>
        </body>
        {/* <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"/> */}

      </html>

    </>
  );
}